FROM nginx

COPY public /usr/share/nginx/html
COPY build /usr/share/nginx/html

-----------------------------------

FROM ubuntu

RUN apt-get update
RUN apt-get install -y nginx

RUN echo "daemon off;" >> /etc/nginx/nginx.conf

COPY public /usr/share/nginx/html
COPY build /usr/share/nginx/html

EXPOSE 80
CMD ["/usr/bin/nginx", "-c", "/etc/nginx/nginx.conf"]